sudo: false
language: node_js
node_js:
  - 8.4
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
  - npm run coveralls
